name: image-stitcher
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  # Pin scipy and pandas to prevent basicpy downgrade issues
  - scipy>=1.14
  - pandas>=2.0.0
  - aicsimageio
  - dask-image
  - numpy
  - ome-zarr
  - zarr
  - psutil
  - pydantic>=2.10.5
  - pydantic-core>=2.27.2
  - pydantic-settings>=2.7.1
  - napari-ome-zarr
  - napari[all]
  - pyqt
  # Core dependencies for image processing
  - tifffile
  - tqdm
  - networkx
  - scikit-image
  - matplotlib
  # Testing dependencies
  - pytest
  # Tensor backend dependencies (optional GPU acceleration)
  # Note: These are optional and the system will fall back to NumPy if not available
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda=12.1  # For CUDA 12.x compatibility
  - pip:
    # Pin hyperactive to a known-good Windows-compatible version
    - hyperactive==4.5.0
    # Install jax with Windows-compatible versions that work with scipy>=1.14
    - "jax[cpu]>=0.4.30,<0.5.0"
    - "jaxlib>=0.4.30,<0.5.0"
    # Install basicpy after jax to prevent dependency conflicts
    - basicpy>=1.2.0
  # CuPy will be installed via pip in setup scripts for better compatibility
  # NOTE: basicpy is now installed via pip above with compatible jax versions.
  # This prevents the scipy 1.15→1.12 downgrade that causes memory allocation
  # failures on Windows systems with limited virtual memory.
